External Review for Back-end API
M-AminAlizadeh/Booking-doctor-appointment-back-end pull request #20
Opened 2023-12-19 21:28 UTC by SaveryIV

2023-12-20 19:30 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!










#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-20 19:30 UTC, Meltrust commented on README.md
> +### Run tests
- [ ] There are 3 backend tests that are not passing:

![image](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-back-end/assets/57421823/acb30ce5-7073-4a43-ba64-50917e0f586f)

Kindly correct them. 👍

2023-12-20 19:30 UTC, Meltrust commented on README.md
> +### Run tests
- [ ]  You are using Rspec, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2023-12-21 12:03 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Readme has been improved✔️




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-21 13:07 UTC, SaveryIV commented
@Meltrust I fixed the tests, and actually delete the folder test

2023-12-21 20:34 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**

## Thank you for the changes implemented 💪 🥇 ㊗️ 



### To highlight

- Most tests have been corrected ✔️ 



Cheers and Happy coding!👏👏👏


------

2023-12-21 20:34 UTC, Meltrust commented on README.md
> +To run tests use `rspec spec`
- [ ] OPTIONAL: One test is still not passing.  I would advise you to correct it before final evaluation:

![image](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-back-end/assets/57421823/7e7b48ac-227d-4991-9c5c-4ed27fa10614)

![image](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-back-end/assets/57421823/f78f2afc-2bed-4043-805e-7f01fd3f19f4)

2023-12-21 21:40 UTC, SaveryIV commented on README.md
> +To run tests use `rspec spec`
In my case is working but i will check

2024-01-12 18:35 UTC, merged